version=2.0.0
artifact=TotalDebugCompanion.jar
downloadUri=https://github.com/Minecraft-TA/TotalDebugCompanion/releases/download/v2.0.0/TotalDebugCompanion.jar
sha256=c7f6bf3f63e918aae939f83ddbae68cf2fad904162a387db779f484ea893ea8a
