version=2.0.0
artifact=TotalDebugCompanion.jar
downloadUri=https://github.com/Minecraft-TA/TotalDebugCompanion/releases/download/v2.0.0/TotalDebugCompanion.jar
sha256=daff2a8669247718f882cd8b355ddabfe417253852b5487c54953634745d5452
