version=2.0.0
artifact=TotalDebugCompanion.jar
downloadUri=https://github.com/Minecraft-TA/TotalDebugCompanion/releases/download/v2.0.0/TotalDebugCompanion.jar
sha256=7f09e350acb7dbcc8a8a994d6ba2a8340b7226e67ae6acf69ba9ee61babf7157
