org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neo_version=21.1.201
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_version=2.0.0-SNAPSHOT

scnet_version=2.0.0
classgraph_version=4.8.193
vineflower_version=1.12.0
jindex_version=1.0.0
