version=3.0.0
artifact=TotalDebugCompanion.jar
downloadUri=https://github.com/Minecraft-TA/TotalDebug/releases/download/v3.0.0/TotalDebugCompanion.jar
sha256=42e3c9721e30f9a223c4c9cb3ea9ab61e6a15fec9e0587819b859f6ab73cd0dd
